# Copyright (c) 2023-2025 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
from __future__ import annotations

from functools import cached_property
from itertools import chain

from pyavd._eos_cli_config_gen.schema import EosCliConfigGen
from pyavd._eos_designs.schema import EosDesigns
from pyavd._eos_designs.structured_config.structured_config_generator import StructuredConfigGenerator, structured_config_contributor
from pyavd._errors import AristaAvdInvalidInputsError
from pyavd.j2filters import natural_sort


class AvdStructuredConfigFlows(StructuredConfigGenerator):
    """
    Structured config for sflow and flow_tracker.

    This class must be rendered after all other eos_designs modules since it relies on
    detecting sflow from the interface structured config generated by the other modules.

    The only exception is of course custom_structured_configuration which always comes last.
    """

    ignore_avd_eos_designs_enforce_duplication_checks_across_all_models = True

    @structured_config_contributor
    def sflow(self) -> None:
        """
        Structured config for sFlow.

        Only configure if any interface is enabled for sFlow.

        Covers:
        - sflow_settings
        - source-interfaces based on source_interfaces.sflow
        """
        if not self._enable_sflow:
            return

        if not (destinations := self.inputs.sflow_settings.destinations):
            msg = "`sflow_settings.destinations` is required to configure `sflow`."
            raise AristaAvdInvalidInputsError(msg)

        sflow_settings_vrfs = self.inputs.sflow_settings.vrfs

        # At this point we have at least one interface with sFlow enabled
        # and at least one destination.
        self.structured_config.sflow._update(
            run=True, polling_interval=self.inputs.sflow_settings.polling_interval, sample=self.inputs.sflow_settings.sample.rate
        )
        sflow_vrfs = EosCliConfigGen.Sflow.Vrfs()

        for destination in natural_sort(destinations, "destination"):
            destination: EosDesigns.SflowSettings.DestinationsItem
            vrf_name = destination.vrf
            if vrf_name is None:
                vrf_name = self.shared_utils.default_mgmt_protocol_vrf
                source_interface = self.shared_utils.default_mgmt_protocol_interface

            elif vrf_name == "use_mgmt_interface_vrf":
                if (self.shared_utils.node_config.mgmt_ip is None) and (self.shared_utils.node_config.ipv6_mgmt_ip is None):
                    msg = "Unable to configure sFlow source-interface with 'use_mgmt_interface_vrf' since 'mgmt_ip' or 'ipv6_mgmt_ip' are not set."
                    raise AristaAvdInvalidInputsError(msg)

                vrf_name = self.inputs.mgmt_interface_vrf
                if vrf_name in sflow_settings_vrfs and sflow_settings_vrfs[vrf_name].source_interface:
                    source_interface = sflow_settings_vrfs[vrf_name].source_interface
                else:
                    source_interface = self.shared_utils.mgmt_interface

            elif vrf_name == "use_inband_mgmt_vrf":
                # Check for missing interface
                if self.shared_utils.inband_mgmt_interface is None:
                    msg = "Unable to configure sFlow source-interface with 'use_inband_mgmt_vrf' since 'inband_mgmt_interface' is not set."
                    raise AristaAvdInvalidInputsError(msg)

                # self.shared_utils.inband_mgmt_vrf returns None for the default VRF, but here we need "default" to avoid duplicates.
                vrf_name = self.shared_utils.inband_mgmt_vrf or "default"
                if vrf_name in sflow_settings_vrfs and sflow_settings_vrfs[vrf_name].source_interface:
                    source_interface = sflow_settings_vrfs[vrf_name].source_interface
                else:
                    source_interface = self.shared_utils.inband_mgmt_interface

            # Default is none, meaning we will not configure a source interface for this VRF.
            elif vrf_name in sflow_settings_vrfs and sflow_settings_vrfs[vrf_name].source_interface:
                source_interface = sflow_settings_vrfs[vrf_name].source_interface
            else:
                source_interface = None

            if vrf_name in [None, "default"]:
                # Add destination without VRF field
                self.structured_config.sflow.destinations.append_new(destination=destination.destination, port=destination.port)
                self.structured_config.sflow.source_interface = source_interface

            else:
                # Add destination with VRF field.
                vrf_item = sflow_vrfs.obtain(vrf_name)
                vrf_item.destinations.append_new(destination=destination.destination, port=destination.port)
                vrf_item.source_interface = source_interface

            self.structured_config.sflow.vrfs = sflow_vrfs

    @cached_property
    def _enable_sflow(self) -> bool:
        """
        Enable sFlow if any interface is enabled for sFlow.

        This relies on sFlow being rendered after all other eos_designs modules (except structured config).
        """
        return any(interface.sflow.enable for interface in chain(self.structured_config.ethernet_interfaces, self.structured_config.port_channel_interfaces))

    def resolve_flow_tracker_by_type(
        self, tracker_settings: EosDesigns.FlowTrackingSettings.TrackersItem
    ) -> EosCliConfigGen.FlowTracking.Hardware.TrackersItem | EosCliConfigGen.FlowTracking.Sampled.TrackersItem:
        if self.shared_utils.flow_tracking_type == "sampled":
            tracker = EosCliConfigGen.FlowTracking.Sampled.TrackersItem(
                name=tracker_settings.name,
                record_export=tracker_settings.record_export._cast_as(EosCliConfigGen.FlowTracking.Sampled.TrackersItem.RecordExport),
                exporters=tracker_settings.exporters._cast_as(EosCliConfigGen.FlowTracking.Sampled.TrackersItem.Exporters),
                table_size=tracker_settings.sampled.table_size,
            )
            tracker.record_export.mpls = tracker_settings.sampled.record_export.mpls
            return tracker
        return EosCliConfigGen.FlowTracking.Hardware.TrackersItem(
            name=tracker_settings.name,
            record_export=tracker_settings.record_export._cast_as(EosCliConfigGen.FlowTracking.Hardware.TrackersItem.RecordExport),
            exporters=tracker_settings.exporters._cast_as(EosCliConfigGen.FlowTracking.Hardware.TrackersItem.Exporters),
        )

    @structured_config_contributor
    def flow_tracking(self) -> None:
        """Set the structured config for flow_tracking."""
        configured_trackers = self._get_enabled_flow_trackers()
        if not configured_trackers:
            return

        structured_config = self.structured_config.flow_tracking
        flow_tracking_settings = self.inputs.flow_tracking_settings

        if self.shared_utils.flow_tracking_type == "hardware":
            structured_config.hardware = flow_tracking_settings.hardware._cast_as(EosCliConfigGen.FlowTracking.Hardware)
            structured_config.hardware.shutdown = False
            tracker_list = structured_config.hardware.trackers
        else:
            structured_config.sampled._update(sample=flow_tracking_settings.sampled.sample, shutdown=False)
            structured_config.sampled.encapsulation._update(
                ipv4_ipv6=flow_tracking_settings.sampled.encapsulation.ipv4_ipv6,
                mpls=flow_tracking_settings.sampled.encapsulation.mpls,
            )
            structured_config.sampled.hardware_offload._update(
                ipv4=flow_tracking_settings.sampled.hardware_offload.ipv4,
                ipv6=flow_tracking_settings.sampled.hardware_offload.ipv6,
                threshold_minimum=flow_tracking_settings.sampled.hardware_offload.threshold_minimum,
            )
            tracker_list = structured_config.sampled.trackers

        default_tracker = next(iter(EosDesigns.FlowTrackingSettings().trackers))
        for tracker_name in natural_sort(configured_trackers):
            """
            We allow overriding the default flow tracker name, so if user has configured a tracker
            with the default tracker name, then we just use that, if not, we create a default config
            """
            if tracker_name not in self.inputs.flow_tracking_settings.trackers:
                if tracker_name == default_tracker.name:
                    tracker = default_tracker
                else:
                    msg = f"{tracker_name} is being used for one of the interfaces, but is not configured in flow_tracking_settings"
                    raise AristaAvdInvalidInputsError(msg)
            else:
                tracker = self.inputs.flow_tracking_settings.trackers[tracker_name]
            tracker_list.append(self.resolve_flow_tracker_by_type(tracker))

    def _get_enabled_flow_trackers(self) -> set[str]:
        """
        Enable flow-tracking if any interface is enabled for flow-tracking.

        This relies on flow-tracking being rendered after all other eos_designs modules (except structured config).
        """
        all_interfaces = chain(
            self.structured_config.ethernet_interfaces, self.structured_config.port_channel_interfaces, self.structured_config.dps_interfaces
        )
        if self.shared_utils.flow_tracking_type == "hardware":
            return {interface.flow_tracker.hardware for interface in all_interfaces if interface.flow_tracker.hardware}

        return {interface.flow_tracker.sampled for interface in all_interfaces if interface.flow_tracker.sampled}
