# Copyright (c) 2023-2025 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
from __future__ import annotations

from functools import cached_property
from itertools import chain

from pyavd._eos_cli_config_gen.schema import EosCliConfigGen
from pyavd._eos_designs.schema import EosDesigns
from pyavd._eos_designs.structured_config.structured_config_generator import StructuredConfigGenerator, structured_config_contributor
from pyavd._errors import AristaAvdInvalidInputsError
from pyavd.j2filters import natural_sort


class AvdStructuredConfigFlows(StructuredConfigGenerator):
    """
    Structured config for sflow and flow_tracker.

    This class must be rendered after all other eos_designs modules since it relies on
    detecting sflow from the interface structured config generated by the other modules.

    The only exception is of course custom_structured_configuration which always comes last.
    """

    ignore_avd_eos_designs_enforce_duplication_checks_across_all_models = True

    @structured_config_contributor
    def sflow(self) -> None:
        """
        Structured config for sFlow.

        Only configure if any interface is enabled for sFlow.

        Covers:
        - sflow_settings
        - source-interfaces based on source_interfaces.sflow
        """
        if not self._enable_sflow:
            return

        if not (destinations := self.inputs.sflow_settings.destinations):
            msg = "`sflow_settings.destinations` is required to configure `sflow`."
            raise AristaAvdInvalidInputsError(msg)

        sflow_settings_vrfs = self.inputs.sflow_settings.vrfs

        # At this point we have at least one interface with sFlow enabled
        # and at least one destination.
        self.structured_config.sflow._update(
            run=True, polling_interval=self.inputs.sflow_settings.polling_interval, sample=self.inputs.sflow_settings.sample.rate
        )
        sflow_vrfs = EosCliConfigGen.Sflow.Vrfs()

        for destination in natural_sort(destinations, "destination"):
            destination: EosDesigns.SflowSettings.DestinationsItem
            vrf = destination.vrf
            if vrf is None:
                vrf = self.shared_utils.default_mgmt_protocol_vrf
                source_interface = self.shared_utils.default_mgmt_protocol_interface

            elif vrf == "use_mgmt_interface_vrf":
                if (self.shared_utils.node_config.mgmt_ip is None) and (self.shared_utils.node_config.ipv6_mgmt_ip is None):
                    msg = "Unable to configure sFlow source-interface with 'use_mgmt_interface_vrf' since 'mgmt_ip' or 'ipv6_mgmt_ip' are not set."
                    raise AristaAvdInvalidInputsError(msg)

                vrf = self.inputs.mgmt_interface_vrf
                if vrf in sflow_settings_vrfs and sflow_settings_vrfs[vrf].source_interface:
                    source_interface = sflow_settings_vrfs[vrf].source_interface
                else:
                    source_interface = self.shared_utils.mgmt_interface

            elif vrf == "use_inband_mgmt_vrf":
                # Check for missing interface
                if self.shared_utils.inband_mgmt_interface is None:
                    msg = "Unable to configure sFlow source-interface with 'use_inband_mgmt_vrf' since 'inband_mgmt_interface' is not set."
                    raise AristaAvdInvalidInputsError(msg)

                # self.shared_utils.inband_mgmt_vrf returns None for the default VRF, but here we need "default" to avoid duplicates.
                vrf = self.shared_utils.inband_mgmt_vrf or "default"
                if vrf in sflow_settings_vrfs and sflow_settings_vrfs[vrf].source_interface:
                    source_interface = sflow_settings_vrfs[vrf].source_interface
                else:
                    source_interface = self.shared_utils.inband_mgmt_interface

            # Default is none, meaning we will not configure a source interface for this VRF.
            elif vrf in sflow_settings_vrfs and sflow_settings_vrfs[vrf].source_interface:
                source_interface = sflow_settings_vrfs[vrf].source_interface
            else:
                source_interface = None

            if vrf in [None, "default"]:
                # Add destination without VRF field
                self.structured_config.sflow.destinations.append_new(destination=destination.destination, port=destination.port)
                self.structured_config.sflow.source_interface = source_interface

            else:
                # Add destination with VRF field.
                vrf_item = sflow_vrfs.obtain(vrf)
                vrf_item.destinations.append_new(destination=destination.destination, port=destination.port)
                vrf_item.source_interface = source_interface

            self.structured_config.sflow.vrfs = sflow_vrfs

    @cached_property
    def _enable_sflow(self) -> bool:
        """
        Enable sFlow if any interface is enabled for sFlow.

        This relies on sFlow being rendered after all other eos_designs modules (except structured config).
        """
        return any(interface.sflow.enable for interface in chain(self.structured_config.ethernet_interfaces, self.structured_config.port_channel_interfaces))

    @structured_config_contributor
    def flow_tracking(self) -> None:
        """Return structured config for flow_tracking."""
        configured_trackers = self._get_enabled_flow_trackers()
        if not configured_trackers:
            return

        tracker_type = self.shared_utils.flow_tracking_type
        structured_config = self.structured_config.flow_tracking
        default_tracker = next(iter(EosDesigns.FlowTrackingSettings().trackers))
        if tracker_type == "hardware":
            structured_config.hardware = self.inputs.flow_tracking_settings.hardware._cast_as(EosCliConfigGen.FlowTracking.Hardware)
            structured_config.hardware.shutdown = False
            filtered_trackers = EosCliConfigGen.FlowTracking.Hardware.Trackers()
            cast_as_tracker = EosCliConfigGen.FlowTracking.Hardware.TrackersItem
            structured_config.hardware.trackers = self._set_flow_tracking_trackers(filtered_trackers, cast_as_tracker, default_tracker, configured_trackers)
        elif tracker_type == "sampled":
            structured_config.sampled.sample = self.inputs.flow_tracking_settings.sampled.sample
            structured_config.sampled.encapsulation._update(
                ipv4_ipv6=self.inputs.flow_tracking_settings.sampled.encapsulation.ipv4_ipv6, mpls=self.inputs.flow_tracking_settings.sampled.encapsulation.mpls
            )
            # asdict does not contain default values so we need to insert the default sample.
            # TODO: consider if asdict should include defaults.
            structured_config.sampled.hardware_offload._update(
                ipv4=self.inputs.flow_tracking_settings.sampled.hardware_offload.ipv4,
                ipv6=self.inputs.flow_tracking_settings.sampled.hardware_offload.ipv6,
                threshold_minimum=self.inputs.flow_tracking_settings.sampled.hardware_offload.threshold_minimum,
            )
            structured_config.sampled.shutdown = False
            filtered_trackers = EosCliConfigGen.FlowTracking.Sampled.Trackers()
            cast_as_tracker = EosCliConfigGen.FlowTracking.Sampled.TrackersItem
            structured_config.sampled.trackers = self._set_flow_tracking_trackers(filtered_trackers, cast_as_tracker, default_tracker, configured_trackers)

    def _get_enabled_flow_trackers(self) -> set[str]:
        """
        Enable flow-tracking if any interface is enabled for flow-tracking.

        This relies on flow-tracking being rendered after all other eos_designs modules (except structured config).
        """
        all_interfaces = chain(
            self.structured_config.ethernet_interfaces, self.structured_config.port_channel_interfaces, self.structured_config.dps_interfaces
        )
        if self.shared_utils.flow_tracking_type == "hardware":
            return {interface.flow_tracker.hardware for interface in all_interfaces if interface.flow_tracker.hardware}

        return {interface.flow_tracker.sampled for interface in all_interfaces if interface.flow_tracker.sampled}

    def _set_flow_tracking_trackers(
        self,
        filtered_trackers: EosCliConfigGen.FlowTracking.Hardware.Trackers | EosCliConfigGen.FlowTracking.Sampled.Trackers,
        cast_as_tracker: EosCliConfigGen.FlowTracking.Sampled.TrackersItem | EosCliConfigGen.FlowTracking.Hardware.TrackersItem,
        default_tracker: EosDesigns.FlowTrackingSettings().trackers,
        configured_trackers: dict,
    ) -> EosCliConfigGen.FlowTracking.Hardware.Trackers | EosCliConfigGen.FlowTracking.Sampled.Trackers:
        """Process and return a list of flow tracking trackers based on the provided configuration."""
        for tracker_name in natural_sort(configured_trackers):
            tracker = self.inputs.flow_tracking_settings.trackers.get(tracker_name, default_tracker if tracker_name == default_tracker.name else None)
            if tracker is None:
                msg = f"{tracker_name} is being used for one of the interfaces, but is not configured in flow_tracking_settings"
                raise AristaAvdInvalidInputsError(msg)

            filtered_trackers.append(tracker._cast_as(cast_as_tracker, ignore_extra_keys=True))

        return filtered_trackers
