# content of pytest.ini
[pytest]
# Capture tee-sys is blocking pytest for Ansible display messages in verify_requirements
# addopts = -ra -q -s -vv --capture=tee-sys
addopts = -ra -q -s -vv --color="yes"
markers =
    module_utils: mark a test to be part of module utils test.
log_level = INFO
log_cli = True
