---
scenario:
  converge_sequence:
    - syntax
    - converge
    - verify
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
  options:
    managed: false
platforms:
  - name: dummy
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: "jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n"
      gathering: explicit
      callbacks_enabled: profile_tasks
  inventory:
    links:
      hosts: "inventory/hosts.yml"
      group_vars: "inventory/group_vars/"
      host_vars: "inventory/host_vars/"
  env:
    # Custom pythonpath to allow loading custom ip_addressing and descriptions modules.
    # See CUSTOM_PYTHON_MODULES_TESTS group vars for details.
    PYTHONPATH: ${PYTHONPATH}:${MOLECULE_SCENARIO_DIRECTORY}/custom_modules
    # Keeping temporary files by overriding the tmp folder. This allows us to track changes here.
    AVDTMPDIR: ${MOLECULE_SCENARIO_DIRECTORY}/tmp
verifier:
  name: ansible
